# Problem: NetHack depends on the files in /nhvar already existing, so you
# can't just mount an empty local directory into it.

FROM debian:jessie
RUN apt-get update && apt-get install -o APT::Install-Recommends=0 \
				      -o APT::Install-Suggests=0 -y \
			bison \
			flex \
			gcc \
			less \
			make \
			man \
			ncompress \
			ncurses-dev \
			wget

RUN wget -O - http://sourceforge.net/projects/nethack/files/nethack/3.4.3/nethack-343-src.tgz | \
	tar zxv -C /tmp && \
	cd /tmp/nethack-3.4.3 && \
	sh sys/unix/setup.sh && \
	sed -i -e 's:/\* \(#define LINUX\) \*/:\1:' \
	       -e 's:/\* \(#define VAR_PLAYGROUND\) "[^"]\+" \*/:\1 "/nhvar":' \
	       include/unixconf.h && \
	sed -i -e '/^WINTTYLIB/s/=.*/= -lncurses/' src/Makefile && \
	sed -i -e '/^MANDIR/s:=.*:= /usr/share/man/man6:' doc/Makefile && \
	sed -i -e '/^VARDIR/s:=.*:= /nhvar:' Makefile && \
	mkdir -p /usr/share/man/man6 && \
	make all && \
	make install && \
	make manpages && \
	cd /tmp && rm -rf nethack-3.4.3

ENV PATH       $PATH:/usr/games
ENV HACKPAGER  /usr/bin/less

# `/root` seems to have special protections that keep NetHack from reading any
# config files in it, so we'll create a user account whose files NetHack _can_
# read.
RUN useradd -d /home/wizard -m -U -s /bin/bash wizard
USER wizard

VOLUME ["/nhvar"]
CMD ["/usr/games/nethack"]
